# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: innovate-ecommerce
spec:
  selector:
    app: backend
  ports:
    - port: 3030
      targetPort: 3030
  type: NodePort

